version: '3.8'

services:
  backend:
    image: quotegen-backend
    ports:
      - "8000:5000"
    container_name: quotegen-backend
    networks:
      - app-network

  frontend:
    image: quotegen-frontend
    ports:
      - "3000:3000"
    container_name: quotegen-frontend
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network: 