apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: quotegen
  labels:
    app: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
    prometheus.io/path: "/metrics"
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    nodePort: 30500
    protocol: TCP 