apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: quotegen
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - name: web
    port: 3000
    targetPort: 3000
    nodePort: 31616
    protocol: TCP 